apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - args:
            - >-
              wget -qO- 
              https://github.com/google/jsonnet/releases/download/v0.17.0/jsonnet-bin-v0.17.0-linux.tar.gz 
              | tar -xvzf -   && mv jsonnet jsonnetfmt /custom-tools/
          command:
            - sh
            - '-c'
          image: alpine:3.8
          name: download-tools
          volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      # volumes:
      # - emptyDir: {}
      #   name: custom-tools
repoServer:
  extraContainers: 
    # add plugin jsonnet-helm-with-crds-plugin.yaml to argocd as side car
    - command:
        - /var/run/argocd/argocd-cmp-server
      image: quay.io/argoproj/argocd:v2.9.0
      name: jsonnet-helm-with-crds
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
          # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: jsonnet-helm-with-crds   # plugin name from configmap
          subPath: plugin.yaml
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /usr/bin/jsonnet
          name: custom-tools
          subPath: jsonnet
    - command:
        - /var/run/argocd/argocd-cmp-server
      image: quay.io/argoproj/argocd:v2.9.0
      name: jsonnet-helm
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: jsonnet-helm    # plugin name from configmap
          subPath: plugin.yaml
        - mountPath: /tmp
          name: cmp-tmp
        # Important: Mount tools into $PATH
        - mountPath: /usr/bin/jsonnet
          name: custom-tools
          subPath: jsonnet
  volumeMounts:
    - mountPath: /usr/local/bin/jsonnet
      name: custom-tools
      subPath: jsonnet
  volumes:
    - emptyDir: {}
      name: custom-tools
    - configMap:
        name: jsonnet-helm-with-crds # from the plugin name created
      name: jsonnet-helm-with-crds
    - configMap:
        name: jsonnet-helm # from the plugin name created
      name: jsonnet-helm
    - emptyDir: {}
      name: cmp-tmp

