apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ca
  namespace: argocd
spec:
  destination:
    server: https://k3s1.k8s.lab:6443
    namespace: cert-manager
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    targetRevision: main
    path: k3s1/apps/cert-manager-ca/ca
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
