#ConfigManagementPlugin for use by sidecar
# Argo CD expects the plugin configuration file to be located at /home/argocd/cmp-server/config/plugin.yaml in the sidecar.
# If you use a custom image for the sidecar, you can add the file directly to that image.
#
#WORKDIR /home/argocd/cmp-server/config/
#COPY plugin.yaml ./
# https://argo-cd.readthedocs.io/en/release-2.8/operator-manual/config-management-plugins/


apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: jsonnet-helm-plugin
spec:
  version: v1.0
  init:
    command: ["/bin/sh", "-c"]
    args: ["mkdir -p ./templates && jsonnet -m . helm-chart.libsonnet && helm dependency build && [ -d './templates' ] && jsonnet ./templates/_templates.jsonnet > ./templates/templates.yaml || exit 0"]
  generate:
    command: ["/bin/sh", "-c"]
    args: ["helm template $ARGOCD_APP_NAME . --api-versions monitoring.coreos.com/v1 --api-versions networking.k8s.io/v1/Ingress --namespace $ARGOCD_APP_NAMESPACE"]
  discover:
    find:
      command: [sh, -c, 'if [ "$ARGOCD_ENV_PLUGIN" = "jsonnet-helm-plugin" ]; then echo Hi; fi' ]

---

apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: jsonnet-helm-with-crds-plugin
spec:
  version: v1.0
  init:
    command: ["/bin/sh", "-c"]
    args: [ "mkdir -p ./templates && jsonnet -m . helm-chart.libsonnet && helm dependency build && [ -f './templates/_templates.jsonnet' ] && jsonnet ./templates/_templates.jsonnet > ./templates/templates.yaml || exit 0" ]
  generate:
    command: ["/bin/sh", "-c"]
    args: [ "helm template $ARGOCD_APP_NAME . --api-versions monitoring.coreos.com/v1 --api-versions networking.k8s.io/v1/Ingress --namespace $ARGOCD_APP_NAMESPACE --include-crds" ]
  discover:
    find:
      command: [ sh, -c, "if [ \"$ARGOCD_ENV_PLUGIN\" = \"jsonnet-helm-with-crds-plugin\" ]; then echo Hi; fi" ]
