extraObjects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: jsonnet-helm
    labels:
      name: jsonnet-helm
    annotations: {}
  data:
    plugin.yaml: |
      apiVersion: argoproj.io/v1alpha1
      kind: ConfigManagementPlugin
      metadata:
        name: jsonnet-helm
      spec:
        version: v1.0
        init:
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p ./templates && jsonnet -m . helm-chart.libsonnet && helm dependency build && [ -d './templates' ] && jsonnet ./templates/_templates.jsonnet > ./templates/templates.yaml || exit 0"]
        generate:
          command: ["/bin/sh", "-c"]
          args: ["helm template $ARGOCD_APP_NAME . --api-versions monitoring.coreos.com/v1 --api-versions networking.k8s.io/v1/Ingress --namespace $ARGOCD_APP_NAMESPACE"]
        discover:
          find:
            command: [sh, -c, 'if [ "$ARGOCD_ENV_PLUGIN" = "jsonnet-helm" ]; then echo Hi; fi' ]

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: jsonnet-helm-with-crds
    labels:
      name: jsonnet-helm-with-crds
    annotations: {}
  data:
    plugin.yaml: |
      apiVersion: argoproj.io/v1alpha1
      kind: ConfigManagementPlugin
      metadata:
        name: jsonnet-helm-with-crds
      spec:
        version: v1.0
        init:
          command: ["/bin/sh", "-c"]
          args: [ "mkdir -p ./templates && jsonnet -m . helm-chart.libsonnet && helm dependency build && [ -f './templates/_templates.jsonnet' ] && jsonnet ./templates/_templates.jsonnet > ./templates/templates.yaml || exit 0" ]
        generate:
          command: ["/bin/sh", "-c"]
          args: [ "helm template $ARGOCD_APP_NAME . --api-versions monitoring.coreos.com/v1 --api-versions networking.k8s.io/v1/Ingress --namespace $ARGOCD_APP_NAMESPACE --include-crds" ]
        discover:
          find:
            command: [ sh, -c, "if [ \"$ARGOCD_ENV_PLUGIN\" = \"jsonnet-helm-with-crds\" ]; then echo Hi; fi" ]

# ---------------------------
# Base Argo CD Settings
# ---------------------------
dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true

server:
  ingress:
    enabled: true
    hosts:
    - argocd-master.k8s.lab
    ingressClassName: nginx
    name: argocd
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  extraArgs: [ "--insecure" ]
  insecure: true

global:
  domain: k8s.lab

configs:
  secret:
    argocdServerAdminPassword: '$2b$12$3peDOQrx3EVLpfCJ.lRQQOSVNBiyjbJ0ofT79qrsdJvU9eTBG.mFm'
    argocdServerAdminPasswordMtime: "{{ .Release.Time }}"
  cm:
    exec.enabled: "true"
repoServer:
  name: repo-server
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: jsonnet-helm-plugin
      configMap:
        name: jsonnet-helm
    - name: jsonnet-helm-with-crds-plugin
      configMap:
        name: jsonnet-helm-with-crds
  volumeMounts:
    - name: custom-tools          # <-- add this
      mountPath: /custom-tools    # <-- same as initContainer so jsonnet is visible in repo-server container
    - name: jsonnet-helm-plugin
      mountPath: /home/argocd/cmp-server/config/jsonnet-helm.yaml
      subPath: plugin.yaml
    - name: jsonnet-helm-with-crds-plugin
      mountPath: /home/argocd/cmp-server/config/jsonnet-helm-with-crds.yaml
      subPath: plugin.yaml
  initContainers:
    - name: install-jsonnet-helm
      image: alpine:3.19
      command: ["sh", "-c"]
      args:
        - wget -qO- https://github.com/google/jsonnet/releases/download/v0.17.0/jsonnet-bin-v0.17.0-linux.tar.gz | tar -xvzf - && mv jsonnet /custom-tools/
      volumeMounts:
        - name: custom-tools      # <- this volume is in initContainer
          mountPath: /custom-tools
  env:
    - name: PATH
      value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 