apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd  ### this namespace must be argocd ns.
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    path: clusters/ctx-k3s-cluster-77/cert-manager-v1.14.4
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      releaseName: cert-manager-v1.14.4
      parameters:
      - name: app
        value: cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
