
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: platform
  source:
    path: clusters/ctx-k3s-cluster-77/longhorn-1.5.3
    repoURL: 'https://github.com/belajarpowershell/k3s-repository'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml        
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
