apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    path: clusters/ctx-k3s-cluster-77/prometheus-25.18.0
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      releaseName: prometheus
      parameters:
      - name: app
        value: $ARGOCD_APP_NAME

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

