apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-slave
  namespace: argocd
spec:
  destination:
    server: https://k3s2.k8s.lab:6443
    namespace: argocd
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.4  # Update this to the latest stable version if needed
    helm:
      values: |
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: true
        server:
          ingress:
            enabled: true
            hostname: argocd2.k8s.lab
            ingressClassName: nginx
            tls: false
          certificate:
            enabled: true
            secretName: argocd-server-tls
            issuer:
              kind: ClusterIssuer
              name: ca-issuer-k8s-lab
          extraArgs:
            - --insecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
