{
  nameOverride: 'argocd',
  fullnameOverride: '',
  kubeVersionOverride: '',
  apiVersionOverrides: {
    certmanager: '',
    cloudgoogle: '',
    autoscaling: '',
  },
  createAggregateRoles: false,
  createClusterRoles: true,
  openshift: {
    enabled: false,
  },
  crds: {
    install: true,
    keep: true,
    annotations: {},
  },
  global: {
    additionalLabels: {},
    revisionHistoryLimit: 3,
    image: {
      repository: 'quay.io/argoproj/argocd',
      tag: '',
      imagePullPolicy: 'IfNotPresent',
    },
    imagePullSecrets: [],
    logging: {
      format: 'text',
      level: 'info',
    },
    statefulsetAnnotations: {},
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    securityContext: {},
    hostAliases: [],
    networkPolicy: {
      create: false,
      defaultDenyIngress: false,
    },
    priorityClassName: '',
    nodeSelector: {},
    tolerations: {},
    affinity: {
      podAntiAffinity: 'soft',
      nodeAffinity: {
        type: 'hard',
        matchExpressions: [],
      },
    },
    topologySpreadConstraints: [],
  },
  configs: {
    cm: {
      create: true,
      annotations: {},
      url: '',
      'application.instanceLabelKey': 'argocd.argoproj.io/instance',
      'server.rbac.log.enforce.enable': false,
      'exec.enabled': false,
      'admin.enabled': true,
      'timeout.reconciliation': '180s',
      'timeout.hard.reconciliation': '0s',
    },
    params: {
      annotations: {},
      'otlp.address': '',
      'controller.status.processors': 20,
      'controller.operation.processors': 10,
      'controller.self.heal.timeout.seconds': 5,
      'controller.repo.server.timeout.seconds': 60,
      'server.insecure': false,
      'server.basehref': '/',
      'server.rootpath': '',
      'server.staticassets': '/shared/app',
      'server.disable.auth': false,
      'server.enable.gzip': false,
      'server.x.frame.options': 'sameorigin',
      'reposerver.parallelism.limit': 0,
      'applicationsetcontroller.policy': 'sync',
      'applicationsetcontroller.enable.progressive.syncs': false,
    },
    rbac: {
      create: true,
      annotations: {},
      'policy.default': '',
      'policy.csv': '',
      scopes: '[groups]',
    },
    gpg: {
      annotations: {},
      keys: {},
    },
    ssh: {
      annotations: {},
      knownHosts: 'bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==\ngithub.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=\ngithub.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl\ngithub.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\ngitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=\ngitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf\ngitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9\nssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\nvs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H\n',
      extraHosts: '',
    },
    tls: {
      annotations: {},
      certificates: {},
    },
    cmp: {
      create: false,
      annotations: {},
      plugins: {},
    },
    clusterCredentials: [],
    credentialTemplates: {},
    credentialTemplatesAnnotations: {},
    repositories: {},
    repositoriesAnnotations: {},
    secret: {
      createSecret: true,
      labels: {},
      annotations: {},
      githubSecret: '',
      gitlabSecret: '',
      bitbucketServerSecret: '',
      bitbucketUUID: '',
      gogsSecret: '',
      extra: {},
      argocdServerAdminPassword: '',
      argocdServerAdminPasswordMtime: '',
    },
    styles: '',
  },
  extraObjects: [],
  controller: {
    name: 'application-controller',
    replicas: 1,
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    args: {},
    extraArgs: [],
    env: [],
    envFrom: [],
    extraContainers: [],
    initContainers: [],
    volumeMounts: [],
    volumes: [],
    statefulsetAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      metrics: 8082,
    },
    hostNetwork: false,
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    readinessProbe: {
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    priorityClassName: '',
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    serviceAccount: {
      create: true,
      name: 'argocd-application-controller',
      annotations: {},
      labels: {},
      automountServiceAccountToken: true,
    },
    metrics: {
      enabled: false,
      applicationLabels: {
        enabled: false,
        labels: [],
      },
      service: {
        annotations: {},
        labels: {},
        servicePort: 8082,
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
      rules: {
        enabled: false,
        namespace: '',
        selector: {},
        additionalLabels: {},
        annotations: {},
        spec: [],
      },
    },
    clusterRoleRules: {
      enabled: false,
      rules: [],
    },
  },
  dex: {
    enabled: true,
    name: 'dex-server',
    extraArgs: [],
    metrics: {
      enabled: false,
      service: {
        annotations: {},
        labels: {},
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
    },
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: 'ghcr.io/dexidp/dex',
      tag: 'v2.35.3',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    initImage: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    env: [],
    envFrom: [],
    extraContainers: [],
    initContainers: [],
    volumeMounts: [],
    volumes: [],
    certificateSecret: {
      enabled: false,
      labels: {},
      annotations: {},
      ca: '',
      key: '',
      crt: '',
    },
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      http: 5556,
      grpc: 5557,
      metrics: 5558,
    },
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    livenessProbe: {
      enabled: false,
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    readinessProbe: {
      enabled: false,
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    serviceAccount: {
      create: true,
      name: 'argocd-dex-server',
      annotations: {},
      automountServiceAccountToken: true,
    },
    servicePortHttp: 5556,
    servicePortHttpName: 'http',
    servicePortGrpc: 5557,
    servicePortGrpcName: 'grpc',
    servicePortMetrics: 5558,
    priorityClassName: '',
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
  },
  redis: {
    enabled: true,
    name: 'redis',
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: 'public.ecr.aws/docker/library/redis',
      tag: '7.0.7-alpine',
      imagePullPolicy: '',
    },
    exporter: {
      enabled: false,
      env: [],
      image: {
        repository: 'public.ecr.aws/bitnami/redis-exporter',
        tag: '1.45.0',
        imagePullPolicy: '',
      },
      containerSecurityContext: {
        runAsNonRoot: true,
        readOnlyRootFilesystem: true,
        allowPrivilegeEscalation: false,
        seccompProfile: {
          type: 'RuntimeDefault',
        },
        capabilities: {
          drop: [
            'ALL',
          ],
        },
      },
      resources: {},
    },
    imagePullSecrets: [],
    extraArgs: [],
    env: [],
    envFrom: [],
    extraContainers: [],
    initContainers: [],
    volumeMounts: [],
    volumes: [],
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    securityContext: {
      runAsNonRoot: true,
      runAsUser: 999,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
    },
    containerPorts: {
      redis: 6379,
      metrics: 9121,
    },
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      allowPrivilegeEscalation: false,
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    servicePort: 6379,
    priorityClassName: '',
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    serviceAccount: {
      create: false,
      name: '',
      annotations: {},
      automountServiceAccountToken: false,
    },
    service: {
      annotations: {},
      labels: {},
    },
    metrics: {
      enabled: false,
      service: {
        type: 'ClusterIP',
        clusterIP: 'None',
        annotations: {},
        labels: {},
        servicePort: 9121,
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
    },
  },
  'redis-ha': {
    enabled: false,
    exporter: {
      enabled: false,
      image: 'public.ecr.aws/bitnami/redis-exporter',
      tag: '1.45.0',
    },
    persistentVolume: {
      enabled: false,
    },
    redis: {
      masterGroupName: 'argocd',
      config: {
        save: '""',
      },
    },
    haproxy: {
      enabled: true,
      metrics: {
        enabled: true,
      },
    },
    image: {
      tag: '7.0.7-alpine',
    },
    topologySpreadConstraints: {
      enabled: false,
      maxSkew: '',
      topologyKey: '',
      whenUnsatisfiable: '',
    },
  },
  externalRedis: {
    host: '',
    username: '',
    password: '',
    port: 6379,
    existingSecret: '',
    secretAnnotations: {},
  },
  server: {
    name: 'server',
    replicas: 1,
    autoscaling: {
      enabled: false,
      minReplicas: 1,
      maxReplicas: 5,
      targetCPUUtilizationPercentage: 50,
      targetMemoryUtilizationPercentage: 50,
      behavior: {},
    },
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    extraArgs: [],
    env: [],
    envFrom: [],
    lifecycle: {},
    extensions: {
      enabled: false,
      image: {
        repository: 'ghcr.io/argoproj-labs/argocd-extensions',
        tag: 'v0.2.1',
        imagePullPolicy: '',
      },
      containerSecurityContext: {
        runAsNonRoot: true,
        readOnlyRootFilesystem: true,
        allowPrivilegeEscalation: false,
        seccompProfile: {
          type: 'RuntimeDefault',
        },
        capabilities: {
          drop: [
            'ALL',
          ],
        },
      },
      resources: {},
    },
    extraContainers: [],
    initContainers: [],
    volumeMounts: [],
    volumes: [],
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      server: 8080,
      metrics: 8082,
    },
    hostNetwork: false,
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    readinessProbe: {
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    livenessProbe: {
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    priorityClassName: '',
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    certificate: {
      enabled: false,
      secretName: 'argocd-server-tls',
      domain: 'argocd.example.com',
      additionalHosts: [],
      duration: '',
      renewBefore: '',
      issuer: {
        group: '',
        kind: '',
        name: '',
      },
      privateKey: {
        rotationPolicy: 'Never',
        encoding: 'PKCS1',
        algorithm: 'RSA',
        size: 2048,
      },
    },
    certificateSecret: {
      enabled: false,
      annotations: {},
      labels: {},
      key: '',
      crt: '',
    },
    service: {
      annotations: {},
      labels: {},
      type: 'ClusterIP',
      nodePortHttp: 30080,
      nodePortHttps: 30443,
      servicePortHttp: 80,
      servicePortHttps: 443,
      servicePortHttpName: 'http',
      servicePortHttpsName: 'https',
      loadBalancerIP: '',
      loadBalancerSourceRanges: [],
      externalIPs: [],
      externalTrafficPolicy: '',
      sessionAffinity: '',
    },
    metrics: {
      enabled: false,
      service: {
        annotations: {},
        labels: {},
        servicePort: 8083,
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
    },
    serviceAccount: {
      create: true,
      name: 'argocd-server',
      annotations: {},
      labels: {},
      automountServiceAccountToken: true,
    },
    ingress: {
      enabled: false,
      annotations: {},
      labels: {},
      ingressClassName: '',
      hosts: [],
      paths: [
        '/',
      ],
      pathType: 'Prefix',
      extraPaths: [],
      tls: [],
      https: false,
    },
    ingressGrpc: {
      enabled: false,
      isAWSALB: false,
      annotations: {},
      labels: {},
      ingressClassName: '',
      awsALB: {
        serviceType: 'NodePort',
        backendProtocolVersion: 'HTTP2',
      },
      hosts: [],
      paths: [
        '/',
      ],
      pathType: 'Prefix',
      extraPaths: [],
      tls: [],
      https: false,
    },
    route: {
      enabled: false,
      annotations: {},
      hostname: '',
      termination_type: 'passthrough',
      termination_policy: 'None',
    },
    GKEbackendConfig: {
      enabled: false,
      spec: {},
    },
    GKEmanagedCertificate: {
      enabled: false,
      domains: [
        'argocd.example.com',
      ],
    },
    GKEfrontendConfig: {
      enabled: false,
      spec: {},
    },
  },
  repoServer: {
    name: 'repo-server',
    replicas: 1,
    autoscaling: {
      enabled: false,
      minReplicas: 1,
      maxReplicas: 5,
      targetCPUUtilizationPercentage: 50,
      targetMemoryUtilizationPercentage: 50,
      behavior: {},
    },
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    extraArgs: [],
    env: [],
    envFrom: [],
    extraContainers: [],
    initContainers: [],
    volumeMounts: [],
    volumes: [],
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      server: 8081,
      metrics: 8084,
    },
    hostNetwork: false,
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    readinessProbe: {
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    livenessProbe: {
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1,
      timeoutSeconds: 1,
    },
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    priorityClassName: '',
    certificateSecret: {
      enabled: false,
      annotations: {},
      labels: {},
      ca: '',
      key: '',
      crt: '',
    },
    service: {
      annotations: {},
      labels: {},
      port: 8081,
      portName: 'https-repo-server',
    },
    metrics: {
      enabled: false,
      service: {
        annotations: {},
        labels: {},
        servicePort: 8084,
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
    },
    clusterRoleRules: {
      enabled: false,
      rules: [],
    },
    serviceAccount: {
      create: true,
      name: '',
      annotations: {},
      labels: {},
      automountServiceAccountToken: true,
    },
    rbac: [],
  },
  applicationSet: {
    enabled: true,
    name: 'applicationset-controller',
    replicaCount: 1,
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    args: {},
    extraArgs: [],
    extraEnv: [],
    extraEnvFrom: [],
    extraContainers: [],
    initContainers: [],
    extraVolumeMounts: [],
    extraVolumes: [],
    metrics: {
      enabled: false,
      service: {
        annotations: {},
        labels: {},
        servicePort: 8085,
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        interval: '30s',
        relabelings: [],
        metricRelabelings: [],
        selector: {},
        scheme: '',
        tlsConfig: {},
        namespace: '',
        additionalLabels: {},
        annotations: {},
      },
    },
    service: {
      annotations: {},
      labels: {},
      port: 7000,
      portName: 'webhook',
    },
    serviceAccount: {
      create: true,
      name: 'argocd-applicationset-controller',
      annotations: {},
      labels: {},
      automountServiceAccountToken: true,
    },
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      metrics: 8080,
      probe: 8081,
      webhook: 7000,
    },
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    readinessProbe: {
      enabled: false,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      timeoutSeconds: 1,
      successThreshold: 1,
      failureThreshold: 3,
    },
    livenessProbe: {
      enabled: false,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      timeoutSeconds: 1,
      successThreshold: 1,
      failureThreshold: 3,
    },
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    priorityClassName: '',
    webhook: {
      ingress: {
        enabled: false,
        annotations: {},
        labels: {},
        ingressClassName: '',
        hosts: [],
        paths: [
          '/api/webhook',
        ],
        pathType: 'Prefix',
        extraPaths: [],
        tls: [],
      },
    },
  },
  notifications: {
    enabled: true,
    name: 'notifications-controller',
    argocdUrl: null,
    pdb: {
      enabled: false,
      labels: {},
      annotations: {},
      minAvailable: '',
      maxUnavailable: '',
    },
    image: {
      repository: '',
      tag: '',
      imagePullPolicy: '',
    },
    imagePullSecrets: [],
    logFormat: '',
    logLevel: '',
    extraArgs: [],
    extraEnv: [],
    extraEnvFrom: [],
    extraContainers: [],
    initContainers: [],
    extraVolumeMounts: [],
    extraVolumes: [],
    context: {},
    secret: {
      create: true,
      annotations: {},
      items: {},
    },
    metrics: {
      enabled: false,
      port: 9001,
      service: {
        annotations: {},
        labels: {},
        portName: 'http-metrics',
      },
      serviceMonitor: {
        enabled: false,
        selector: {},
        additionalLabels: {},
        annotations: {},
        scheme: '',
        tlsConfig: {},
        relabelings: [],
        metricRelabelings: [],
      },
    },
    notifiers: {},
    deploymentAnnotations: {},
    podAnnotations: {},
    podLabels: {},
    resources: {},
    containerPorts: {
      metrics: 9001,
    },
    dnsConfig: {},
    dnsPolicy: 'ClusterFirst',
    containerSecurityContext: {
      runAsNonRoot: true,
      readOnlyRootFilesystem: true,
      allowPrivilegeEscalation: false,
      seccompProfile: {
        type: 'RuntimeDefault',
      },
      capabilities: {
        drop: [
          'ALL',
        ],
      },
    },
    nodeSelector: {},
    tolerations: [],
    affinity: {},
    topologySpreadConstraints: [],
    priorityClassName: '',
    serviceAccount: {
      create: true,
      name: 'argocd-notifications-controller',
      annotations: {},
      labels: {},
      automountServiceAccountToken: true,
    },
    cm: {
      create: true,
    },
    subscriptions: [],
    templates: {},
    triggers: {},
  },
}
