apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps1
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    targetRevision: main
    path: k3s1/apps
    directory:
      recurse: true 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

