apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git  # Your Git repo
    targetRevision: main
    path: k3s1/apps  # Points to Jsonnet files
    directory:
      recurse: true  # Ensure all Jsonnet files are processed
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
