apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: platform-component
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.4 # Update this to the latest stable version if needed
    helm:
      values: |
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: true
        server:
          ingress:
            enabled: true
            hostname: argocd1.k8s.lab
            ingressClassName: nginx
            tls: false
          extraArgs:
            - --insecure

#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
