
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    path: app-of-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  syncPolicy:
    #automated:
     #selfHeal: true
    syncOptions:
    - CreateNamespace=true  
