apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imagepullsecret-patcher
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/belajarpowershell/k3s-repository.git
    path: clusters/ctx-k3s-cluster-77/imagepullsecret-patcher
    targetRevision: HEAD
    plugin:
      env:
        - name: PLUGIN
          value: jsonnet-helm-with-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    #automated:
      #selfHeal: true
    syncOptions:
    - CreateNamespace=true
