# to deply argocd on remote cluster, clusterrolebinding must already be configured
# Apply manually on k3s2
# <argocd-clusterrolebinding.yaml>
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: argocd-cluster-admin
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
#   - kind: ServiceAccount
#     name: argocd-application-controller
#     namespace: argocd

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-k3s2
  namespace: argocd
spec:
  destination:
    server: https://k3s2.k8s.lab:6443
    namespace: argocd
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.4 # Update this to the latest stable version if needed
    helm:
      values: |
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: true
        server:
          ingress:
            enabled: true
            hostname: argocd2.k8s.lab
            ingressClassName: nginx
            tls: false
          extraArgs:
            - --insecure

#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
