---
# Source: imagepullsecret-patcher/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullsecret-patcher
  labels:
    helm.sh/chart: imagepullsecret-patcher-1.0.0
    app.kubernetes.io/name: imagepullsecret-patcher
    app.kubernetes.io/instance: imagepullsecret-patcher
    app.kubernetes.io/version: "0.14"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imagepullsecret-patcher
      app.kubernetes.io/instance: imagepullsecret-patcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imagepullsecret-patcher
        app.kubernetes.io/instance: imagepullsecret-patcher
    spec:
      automountServiceAccountToken: true
      serviceAccountName: imagepullsecret-patcher
      securityContext:
        {}
      containers:
        - name: imagepullsecret-patcher
          env:
            - name: CONFIG_FORCE
              value: "true"
            - name: CONFIG_DEBUG
              value: "false"
            - name: CONFIG_MANAGEDONLY
              value: "false"
            - name: CONFIG_RUNONCE
              value: "false" 
            - name: CONFIG_ALLSERVICEACCOUNT
              value: "true" 
            - name: CONFIG_SECRETNAME
              value: ""
            - name: CONFIG_DOCKERCONFIGJSONPATH
              value: "/app/secrets/.dockerconfigjson"
            - name: CONFIG_LOOP_DURATION
              value: "10"
          securityContext:
            {}
          image: "quay.io/titansoft/imagepullsecret-patcher:v0.14"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: src-dockerconfigjson
              mountPath: "/app/secrets"
              readOnly: true
          resources:
            requests:
              cpu: 0.1
              memory: 15Mi
            limits:
              cpu: 0.2
              memory: 30Mi
      volumes:
        - name: src-dockerconfigjson
          secret: 
            secretName:
