# ---------------------------
# Base Argo CD Settings
# ---------------------------
dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true

server:
  ingress:
    enabled: true
    hosts:
    - argocd-master.k8s.lab
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  extraArgs: [ "--insecure" ]
  insecure: true

global:
  domain: k8s.lab

configs:
  secret:
    argocdServerAdminPassword: '$2b$12$3peDOQrx3EVLpfCJ.lRQQOSVNBiyjbJ0ofT79qrsdJvU9eTBG.mFm'
    argocdServerAdminPasswordMtime: "{{ .Release.Time }}"
